### ISSUE TITLE
The Readme needs more cat pictures!

### ISSUE THREAD

**Issue by rachelmyers** [Missmeka/hello-world#3]
I like cats, so I'd suggest adding more cat pictures to the Readme!

I really like this one:
![screen shot 2015-02-10 at 6 39 52 pm](https://cloud.githubusercontent.com/assets/209641/6123287/4079795e-b154-11e4-81ca-27fb1e5e1206.png)

**Comment by Missmeka** [comment]
![img_5436](https://cloud.githubusercontent.com/assets/8888966/6123358/809c7d1e-b155-11e4-9588-8953c5d632d5.JPG)

That is totally a cute cat picture, but I think this fluffy one is pretty good too. What do you think?

**Comment by rachelmyers** [comment]
Oh, I love that picture of Penny is great! I'll create a PR!

**Comment by rachelmyers** [comment]
:tada: :racehorse: :balloon:
